In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# opens and proccess data for future use
with open('iris/iris.data', 'r') as data:
    iris_names = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
    iris_set = [0, 1, 2]
    iris_data = data.read()
    iris_data = iris_data[:-1].split('\n')
    
    for i in range(len(iris_data)):
        iris_data[i] = iris_data[i].split(',')
    for i in range(len(iris_data)):
        c = iris_data[i][-1]
        if c == 'Iris-setosa':
            iris_class = 0
        elif c == 'Iris-versicolor':
            iris_class = 1
        elif c == 'Iris-virginica':
            iris_class = 2
        iris_data[i][-1] = iris_class
        iris_data[i] = [float(atribute) for atribute in iris_data[i][:]]
        iris_data[i][-1] = int(iris_data[i][-1])
    
    iris = np.array(iris_data)
    iris_features = iris[:,0:-1]
    iris_classes = iris[:,-1]

# Questão 1
#### Utilizando a base de dados Iris, disponível no link abaixo, e a linguagem de programação de sua preferência, calcule para cada classe:

a) O vetor médio

In [3]:
mean_vector = []

def calc_mean(dataset):
    return np.mean(dataset, axis=0)

for i in iris_set:
    mean_vector.append(calc_mean(iris_features[np.where(iris_classes == i)]))
    print(f'{iris_names[i]} mean vector = {mean_vector[i]}')

Iris-setosa mean vector = [5.006 3.418 1.464 0.244]
Iris-versicolor mean vector = [5.936 2.77  4.26  1.326]
Iris-virginica mean vector = [6.588 2.974 5.552 2.026]


b) O vetor de desvio padrão para cada característica da base de dados

In [4]:
std_vector = []

def calc_stddev(dataset):
    return np.std(dataset, axis=0, ddof=1)
for i in iris_set:
    std_vector.append(calc_stddev(iris_features[np.where(iris_classes == i)]))
    print(f'{iris_names[i]} standard deviation vector = {std_vector[i]}')

Iris-setosa standard deviation vector = [0.35248969 0.3810244  0.17351116 0.1072095 ]
Iris-versicolor standard deviation vector = [0.51617115 0.31379832 0.46991098 0.19775268]
Iris-virginica standard deviation vector = [0.63587959 0.32249664 0.5518947  0.27465006]


c) O vetor máximo para cada característica da base de dados


In [5]:
for i in iris_set:
    max_vector = np.max(iris_features[np.where(iris_classes == i)], axis=0)
    print(f'{iris_names[i]} max vector = {max_vector}')

Iris-setosa max vector = [5.8 4.4 1.9 0.6]
Iris-versicolor max vector = [7.  3.4 5.1 1.8]
Iris-virginica max vector = [7.9 3.8 6.9 2.5]


d) O vetor mínimo para cada característica da base de dados

In [6]:
for i in iris_set:
    min_vector = np.min(iris_features[np.where(iris_classes == i)], axis=0)
    print(f'{iris_names[i]} min vector = {min_vector}')

Iris-setosa min vector = [4.3 2.3 1.  0.1]
Iris-versicolor min vector = [4.9 2.  3.  1. ]
Iris-virginica min vector = [4.9 2.2 4.5 1.4]


e) A matriz de dispersão


In [7]:
def calc_disp_matrix(dataset):
    x = dataset - calc_mean(dataset)
    return np.dot(x.T, x)

disp_matrix = []

for i in iris_set:
    disp_matrix.append(calc_disp_matrix(iris_features[np.where(iris_classes == i)]))
    print(f'{iris_names[i]} disp matrix = \n{disp_matrix[i]}\n')

Iris-setosa disp matrix = 
[[6.0882 4.9146 0.7908 0.5168]
 [4.9146 7.1138 0.5724 0.5604]
 [0.7908 0.5724 1.4752 0.2792]
 [0.5168 0.5604 0.2792 0.5632]]

Iris-versicolor disp matrix = 
[[13.0552  4.174   8.962   2.7332]
 [ 4.174   4.825   4.05    2.019 ]
 [ 8.962   4.05   10.82    3.582 ]
 [ 2.7332  2.019   3.582   1.9162]]

Iris-virginica disp matrix = 
[[19.8128  4.5944 14.8612  2.4056]
 [ 4.5944  5.0962  3.4976  2.3338]
 [14.8612  3.4976 14.9248  2.3924]
 [ 2.4056  2.3338  2.3924  3.6962]]



f) A matriz de covariância

In [8]:
def calc_cov_matrix(dataset):
    n = len(dataset)
    return calc_disp_matrix(dataset)/(n-1)

cov_matrix = []

for i in iris_set:
    cov_matrix.append(calc_cov_matrix(iris_features[np.where(iris_classes == i)]))
    print(f'{iris_names[i]} covariance matrix = \n{cov_matrix[i]}\n')

Iris-setosa covariance matrix = 
[[0.12424898 0.10029796 0.01613878 0.01054694]
 [0.10029796 0.14517959 0.01168163 0.01143673]
 [0.01613878 0.01168163 0.03010612 0.00569796]
 [0.01054694 0.01143673 0.00569796 0.01149388]]

Iris-versicolor covariance matrix = 
[[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]

Iris-virginica covariance matrix = 
[[0.40434286 0.09376327 0.3032898  0.04909388]
 [0.09376327 0.10400408 0.07137959 0.04762857]
 [0.3032898  0.07137959 0.30458776 0.04882449]
 [0.04909388 0.04762857 0.04882449 0.07543265]]



g) A matriz de correlação


In [9]:
def calc_corr_matrix(dataset):
    stddev = np.array(calc_stddev(dataset))[np.newaxis]
    return calc_cov_matrix(dataset) * 1/(stddev.T*stddev)

corr_matrix = []

for i in iris_set:
    corr_matrix.append(calc_corr_matrix(iris_features[np.where(iris_classes == i)]))
    print(f'{iris_names[i]} correlation matrix = \n{corr_matrix[i]}\n')

Iris-setosa correlation matrix = 
[[1.         0.74678037 0.26387409 0.27909157]
 [0.74678037 1.         0.17669463 0.27997289]
 [0.26387409 0.17669463 1.         0.30630821]
 [0.27909157 0.27997289 0.30630821 1.        ]]

Iris-versicolor correlation matrix = 
[[1.         0.52591072 0.75404896 0.54646107]
 [0.52591072 1.         0.56052209 0.66399872]
 [0.75404896 0.56052209 1.         0.78666809]
 [0.54646107 0.66399872 0.78666809 1.        ]]

Iris-virginica correlation matrix = 
[[1.         0.45722782 0.86422473 0.28110771]
 [0.45722782 1.         0.40104458 0.53772803]
 [0.86422473 0.40104458 1.         0.32210822]
 [0.28110771 0.53772803 0.32210822 1.        ]]



h) As duas componentes principais de maior magnitude dos dados


In [10]:
eigenvalues, eigenvectors = np.linalg.eig(calc_cov_matrix(iris_features))
# eigenvalues are already sorted (uncomment below to check), so we take the 2 first columns in the eigenvectors matrix
# print(eigenvalues)
# print(eigenvectors)
pca_2 = eigenvectors[:,:2] #column vector form of first 2 principal components
print(pca_2)

[[ 0.36158968 -0.65653988]
 [-0.08226889 -0.72971237]
 [ 0.85657211  0.1757674 ]
 [ 0.35884393  0.07470647]]


i) A projeção dos dados nas duas maiores componentes principais

In [11]:
data_projected = np.dot(iris_features, pca_2)
print(data_projected)

[[ 2.82713597 -5.64133105]
 [ 2.79595248 -5.14516688]
 [ 2.62152356 -5.17737812]
 [ 2.7649059  -5.00359942]
 [ 2.78275012 -5.64864829]
 [ 3.23144574 -6.06250644]
 [ 2.69045242 -5.23261922]
 [ 2.8848611  -5.48512908]
 [ 2.62338453 -4.7439257 ]
 [ 2.83749841 -5.20803203]
 [ 3.00481631 -5.96665874]
 [ 2.89820038 -5.33624436]
 [ 2.72390912 -5.08698354]
 [ 2.28614265 -4.81144382]
 [ 2.86779988 -6.50091863]
 [ 3.12747377 -6.65947808]
 [ 2.88881689 -6.13281341]
 [ 2.86302037 -5.6338604 ]
 [ 3.31226514 -6.19396782]
 [ 2.92399691 -5.83519737]
 [ 3.2008114  -5.71259155]
 [ 2.96810819 -5.75475549]
 [ 2.2954854  -5.4563393 ]
 [ 3.20821456 -5.42024641]
 [ 3.15517201 -5.28351414]
 [ 3.00342587 -5.17566739]
 [ 3.0422871  -5.45261105]
 [ 2.94895215 -5.68940829]
 [ 2.87152183 -5.6340138 ]
 [ 2.87849519 -5.1246479 ]
 [ 2.92288105 -5.11733065]
 [ 3.10126576 -5.73280374]
 [ 2.86370642 -6.13470636]
 [ 2.91418362 -6.41474566]
 [ 2.83749841 -5.20803203]
 [ 2.64434325 -5.39191683]
 [ 2.88611463 -5.92152374]
 

# Questão 2
#### Implemente o algoritmo do k-means na linguagem de programação de sua preferência e inicialize este algoritmo com k=3 centros c1=[5.1,3.5,1.4,0.2], c2=[4.9,3.0,1.4,0.2], c3=[4.7,3.2,1.3,0.2].

In [12]:
# def dist(a, b):
#     return np.linalg.norm(np.array(a) - np.array(b))

def kmeans(dataset, K, centroids, stop_condition):
    curr_centroids = centroids
    last_centroids = centroids
    changes = True
#     iterations=0
    while changes:
        clusters = [[] for i in range(K)]
        for i in range(len(dataset)):
            distances = [np.linalg.norm(dataset[i] - c) for c in curr_centroids]
            clusters[np.argmin(distances)].append(dataset[i])
        curr_centroids = [np.mean(c, axis=0) for c in clusters]
        changes = (np.linalg.norm(np.array(curr_centroids) - np.array(last_centroids) > stop_condition))
        last_centroids = curr_centroids
#         iterations+=1

#     print(iterations)
    return clusters, curr_centroids

a) Após a convergência, qual o valor dos centros?

In [13]:
c1 = [5.1,3.5,1.4,0.2]
c2= [4.9,3.0,1.4,0.2]
c3= [4.7,3.2,1.3,0.2]

clusters, centroids = kmeans(iris_features, 3, [c1, c2, c3], 0)
for c in centroids:
    print(c)

[6.85384615 3.07692308 5.71538462 2.05384615]
[5.88360656 2.74098361 4.38852459 1.43442623]
[5.006 3.418 1.464 0.244]


b) Qual o centro mais próximo do centro da classe “Iris-setosa”
<br />
c) Qual o centro mais próximo do centro da classe “Iris-versicolor”
<br />
d) Qual o centro mais próximo do centro da classe “Iris-virginica”

In [14]:
setosa_centroid = calc_mean(iris_features[np.where(iris_classes == 0)])
near_setosa = centroids[np.argmin([np.linalg.norm(c - setosa_centroid) for c in centroids])]
print('a) Setosa nearest centroid:')
# print(setosa_centroid)
print(near_setosa)
print()

versicolor_centroid = calc_mean(iris_features[np.where(iris_classes == 1)])
near_versicolor = centroids[np.argmin([np.linalg.norm(c - versicolor_centroid) for c in centroids])]
print('a) Versicolor nearest centroid:')
# print(versicolor_centroid)
print(near_versicolor)
print()

virginica_centroid = calc_mean(iris_features[np.where(iris_classes == 2)])
near_virginica = centroids[np.argmin([np.linalg.norm(c - virginica_centroid) for c in centroids])]
print('a) Virginica nearest centroid:')
# print(virginica_centroid)
print(near_virginica)



a) Setosa nearest centroid:
[5.006 3.418 1.464 0.244]

a) Versicolor nearest centroid:
[5.88360656 2.74098361 4.38852459 1.43442623]

a) Virginica nearest centroid:
[6.85384615 3.07692308 5.71538462 2.05384615]


# Questão 3
#### Implemente o algoritmo do KNN na linguagem de programação de sua preferência.

In [15]:
def most_common(lst):
    return max(set(lst), key=lst.count)

def knn(dataset, sample, k):
    #dataset: (attributes, class labels)
    data = dataset[:, 0:-1]
    labels = dataset[:, -1]
    test_sample = np.array(sample)
    
    total_dist = data - test_sample                          # numpy automatically creates a repeated array of test_sample
    norm = np.sum(total_dist*total_dist, axis=1)
    neighbors = list(zip(norm, labels))                      # create list of tuples (square of distance, label of class)
    neighbors = sorted(neighbors, key=lambda tup: tup[0])    # sort neighbors by distance
    closest_n = [atribute[1] for atribute in neighbors[:k]]
    
    return most_common(closest_n)

In [16]:
training, test = train_test_split(iris, test_size = 0.3)
# print(test[0][0])
# print(trainning[0])
success_rate = 0
for sample in test:
    n = knn(training, sample[:-1], 3)
    success_rate += (n == sample[-1])

success_rate /= len(test)
print(success_rate)

0.9333333333333333


# Questão 4
#### Implemente um classificador de distância mínima na linguagem de sua preferência.

In [17]:
def minimum_distance_classifier(training_set, sample):
    data = training_set[:, 0:-1]
    labels = training_set[:,-1]
    
    classes = set([int(i) for i in labels])
    centroids = [[] for i in range(len(classes))]
    for i in classes:
        centroids[i] = calc_mean(data[np.where(labels == i)])
    closest_centroid = np.argmin([np.linalg.norm(c - sample) for c in centroids])
    
    return closest_centroid

In [18]:
training, test = train_test_split(iris, test_size = 0.3)
# print(test[0][0])
# print(trainning[0])
success_rate = 0
for sample in test:
    n = minimum_distance_classifier(training, sample[:-1])
    success_rate += (n == sample[-1])

success_rate /= len(test)
print(success_rate)


0.9111111111111111


# Questão 5
#### Implemente uma função discriminante utilizando o log da probabilidade a posteriori para cada uma das classes da base de dados Iris.

<center>
    $g_i(x) = -\frac{1}{2}(\mathbf{x}-\mathbf{\mu_i})^T \mathbf{\Sigma_i^{-1}}(\mathbf{x}-\mathbf{\mu_i})- \frac{d}{2}ln(2\pi)-\frac{1}{2}ln(\left | \mathbf{\Sigma_i} \right |) + ln(P(\omega_i))$
</center>

Retirando o termo comum a todas as classes:

<center>
    $g_i(x) = -\frac{1}{2}(\mathbf{x}-\mathbf{\mu_i})^T \mathbf{\Sigma_i^{-1}}(\mathbf{x}-\mathbf{\mu_i})-\frac{1}{2}ln(\left | \mathbf{\Sigma_i} \right |) + ln(P(\omega_i))$
</center>

In [19]:
def log_discriminant(sample, class_mean, class_cov, class_prob):
    cov_inv = np.linalg.inv(class_cov)
    g = -0.5*np.dot(np.dot((sample - class_mean), cov_inv), (sample - class_mean).T) - 0.5*np.log(np.linalg.det(class_cov)) + np.log(class_prob)
    
    return g

# Questão 6

#### Implemente um classificador bayesiano para a base de dados Iris.

In [20]:
def bayesian_classifier(training_set, sample):
    data = training_set[:, 0:-1]
    labels = training_set[:,-1]
    
    classes = set([int(i) for i in labels])
    set_size = len(data)
    g = [[] for i in classes]
    
    for i in classes:
        p_priori = len(data[np.where(labels == i)])/set_size
        g[i] = log_discriminant(sample, calc_mean(data[np.where(labels == i)]), calc_cov_matrix(data[np.where(labels == i)]), p_priori)
#         print(f'g[{i}] = {g[i]}')
#         print(g[i])
    
    return np.argmax(np.array(g))

In [21]:
training, test = train_test_split(iris, test_size = 0.3)
# print(test[0][0])
# print(trainning[0])
success_rate_bayesian = 0

for sample in test:
    n = bayesian_classifier(training, sample[:-1])
    success_rate_bayesian += (n == sample[-1])
    
success_rate_bayesian /= len(test)
print(success_rate_bayesian)

0.9555555555555556


# Questão 7
#### Implemente um classificador bayesiano para a base de dados Iris projetada sobre as duas maiores componentes principais.

In [22]:
# concatenates classes to PCA components of data
new_data_projected = np.concatenate((data_projected, np.array(iris_classes[np.newaxis]).T), 1)

training, test = train_test_split(new_data_projected, test_size = 0.3)
# print(test[0][0])
# print(trainning[0])
success_rate_bayesian_PCA = 0

for sample in test:
    n = bayesian_classifier(training, sample[:-1])
    success_rate_bayesian_PCA += (n == sample[-1])
    
success_rate_bayesian_PCA /= len(test)
print(success_rate_bayesian_PCA)

0.9111111111111111


# Questão 8
#### Determine o erro percentual e o desvio padrão do erro(quando for possível) nos conjuntos de treinamento e validação dos classificadores implementados nas questões 3,4, 6 e 7 utilizando os seguintes métodos de particionamento de dados:


a) Hold-out com 90% das amostras para treinamento e 10% para validação;

In [23]:
def evaluate_error(classifier, training, test, extrArgs = []):
    error_rate = 0
    
    for sample in test:
        if classifier == knn:
            n = classifier(training, sample[:-1], extrArgs[0])
        else:
            n = classifier(training, sample[:-1])
        error_rate[n][sample[-1]] += not(n == sample[-1])
        
    return error_rate/len(test)

In [24]:
training, test = train_test_split(iris, test_size = 0.1)

print(f'KNN error rate: {evaluate_error(knn, training, test, [3])}')
print(f'Minimum distance error rate: {evaluate_error(minimum_distance_classifier, training, test)}')
print(f'Bayesian error rate: {evaluate_error(bayesian_classifier, training, test)}')
# print(f'Bayesian error rate: {holdout(bayesian_classifier, iris, 0.1)}')

KNN error rate: 0.06666666666666667
Minimum distance error rate: 0.06666666666666667
Bayesian error rate: 0.0


b) Cross-validation 10-folds

In [25]:
def split_folds(dataset, k):
    data_cpy = dataset.copy()
    np.random.shuffle(data_cpy)            # desordena conjunto de dados
    folds = np.split(data_cpy, k)          # divide os grupos
    return folds

def kfolds(classifier, dataset, k, extrArgs = []):
    folds = split_folds(dataset, k)
    error_array = []

    for i, fold in enumerate(folds):
        folds_cpy = folds.copy()           # cria cópia dos grupos
        test = folds_cpy.pop(i)            # separa grupo i para teste
        training = np.vstack(folds_cpy)    # agrupa demais grupos para treinamento
        error_array = np.append(error_array, evaluate_error(classifier, training, test, extrArgs))
    
    return np.mean(error_array), np.std(error_array)

In [26]:
print(f'KNN error rate {kfolds(knn, iris, 10, [3])}')
print(f'Minimum distance error rate {kfolds(minimum_distance_classifier, iris, 10)}')
print(f'Bayesian error rate {kfolds(bayesian_classifier, iris, 10)}')

KNN error rate (0.04, 0.044221663871405324)
Minimum distance error rate (0.08666666666666667, 0.05206833117271103)
Bayesian error rate (0.02, 0.03055050463303893)


c) Monte-Carlo Cross Validation com 90% das amostras para treinamento e 10% para validação

In [27]:
def monte_carlo(classifier, dataset, test_size, k, extrArgs = []):
    error_array = []
    
    for i in range(k):
        training, test = train_test_split(dataset, test_size = test_size)
        error_array = np.append(error_array, evaluate_error(classifier, training, test, extrArgs))
    
    return np.mean(error_array), np.std(error_array)

In [28]:
print(f'KNN error rate {monte_carlo(knn, iris, 0.1, 10, [3])}')
print(f'Minimum distance error rate {monte_carlo(minimum_distance_classifier, iris, 0.1, 10)}')
print(f'Bayesian error rate {monte_carlo(bayesian_classifier, iris, 0.1, 10)}')

KNN error rate (0.02, 0.030550504633038933)
Minimum distance error rate (0.09333333333333334, 0.0679869268479038)
Bayesian error rate (0.02, 0.03055050463303893)


# Questão 9
#### Repita as avaliações da questão 6, calculando a matriz de confusão do erro percentual para cada um dos métodos de particionamento (Houldout, Cross-Validation 10-folds, Monte Carlo Cross-Validation).


In [65]:
def calc_confusion_matrix(classifier, training, test, extrArgs = []):
    classes = set([i[-1] for i in training])
    n_classes = len(classes)
    confusion_matrix = np.zeros((n_classes, n_classes))
    
    for sample in test:
        if classifier == knn:
            n = classifier(training, sample[:-1], extrArgs[0])
        else:
            n = classifier(training, sample[:-1])
        confusion_matrix[int(n)][int(sample[-1])] += 1
        
    return 100*confusion_matrix/confusion_matrix.sum()

In [73]:
training, test = train_test_split(iris, test_size = 0.3)

print(f'KNN confusion matrix: \n{calc_confusion_matrix(knn, training, test, [3]).T}\n')
print(f'Minimum distance confusion matrix: \n{calc_confusion_matrix(minimum_distance_classifier, training, test).T}\n')
print(f'Bayesian confusion matrix: \n{calc_confusion_matrix(bayesian_classifier, training, test).T}')

KNN confusion matrix: 
[[35.55555556  0.          0.        ]
 [ 0.         33.33333333  0.        ]
 [ 0.          4.44444444 26.66666667]]

Minimum distance confusion matrix: 
[[35.55555556  0.          0.        ]
 [ 0.         31.11111111  2.22222222]
 [ 0.          4.44444444 26.66666667]]

Bayesian confusion matrix: 
[[35.55555556  0.          0.        ]
 [ 0.         31.11111111  2.22222222]
 [ 0.          0.         31.11111111]]
