In [231]:
import numpy as np
from sklearn.model_selection import train_test_split

In [73]:
# opens and proccess data for future use
with open('iris/iris.data', 'r') as data:
    iris_classnames = []
    iris_data = data.read()
    iris_data = iris_data[:-1].split('\n')
    
    for i in range(len(iris_data)):
        iris_data[i] = iris_data[i].split(',')
    for i in range(len(iris_data)):
        iris_classnames.append(iris_data[i][-1])
        iris_data[i] = [float(atribute) for atribute in iris_data[i][:-1]]
    
    iris = np.array(iris_data)

# Questão 1
#### Utilizando a base de dados Iris, disponível no link abaixo, e a linguagem de programação de sua preferência, calcule para cada classe:

a) O vetor médio

In [46]:
mean_vector = np.mean(iris_data, axis=0)
print([x for x in mean_vector])

[5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]


b) O vetor de desvio padrão para cada característica da base de dados

In [47]:
std_vector = np.std(iris_data, axis=0, ddof=1)
print([x for x in std_vector])

[0.8280661279778629, 0.4335943113621737, 1.7644204199522617, 0.7631607417008414]


c) O vetor máximo para cada característica da base de dados


In [48]:
max_vector = np.max(iris_data, axis=0)
print([x for x in max_vector])

[7.9, 4.4, 6.9, 2.5]


d) O vetor mínimo para cada característica da base de dados

In [49]:
max_vector = np.min(iris_data, axis=0)
print([x for x in max_vector])

[4.3, 2.0, 1.0, 0.1]


e) A matriz de dispersão


In [62]:
n_columns = len(mean_vector)
n_samples = len(iris_data)
disp_matrix = np.dot(np.array([iris[i] - mean_vector for i in range(len(iris_data))]).T, ([iris[i] - mean_vector for i in range(len(iris_data))]))
print(disp_matrix)

[[102.16833333  -5.851      189.77866667  77.01866667]
 [ -5.851       28.0126     -47.9352     -17.5792    ]
 [189.77866667 -47.9352     463.86373333 193.16173333]
 [ 77.01866667 -17.5792     193.16173333  86.77973333]]


f) A matriz de covariância

In [63]:
cov_matrix = disp_matrix/(n_samples - 1)
print(cov_matrix)

[[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]


g) A matriz de correlação


In [61]:
corr_matrix = cov_matrix * 1/np.dot(std_vector[np.newaxis].T, std_vector[np.newaxis])

print(corr_matrix)

[[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]


h) As duas componentes principais de maior magnitude dos dados


In [68]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
#eigenvalues are already sorted (uncomment below to check), so we take the 2 first columns in the eigenvectors matrix
# print(eigenvalues)
# print(eigenvectors)
pca_2 = eigenvectors[:,:2] #column vector form of first 2 principal components
print(pca_2)

[[ 0.36158968 -0.65653988]
 [-0.08226889 -0.72971237]
 [ 0.85657211  0.1757674 ]
 [ 0.35884393  0.07470647]]


i) A projeção dos dados nas duas maiores componentes principais

In [70]:
data_projected = np.dot(iris, pca_2)
print(data_projected)

[[ 2.82713597 -5.64133105]
 [ 2.79595248 -5.14516688]
 [ 2.62152356 -5.17737812]
 [ 2.7649059  -5.00359942]
 [ 2.78275012 -5.64864829]
 [ 3.23144574 -6.06250644]
 [ 2.69045242 -5.23261922]
 [ 2.8848611  -5.48512908]
 [ 2.62338453 -4.7439257 ]
 [ 2.83749841 -5.20803203]
 [ 3.00481631 -5.96665874]
 [ 2.89820038 -5.33624436]
 [ 2.72390912 -5.08698354]
 [ 2.28614265 -4.81144382]
 [ 2.86779988 -6.50091863]
 [ 3.12747377 -6.65947808]
 [ 2.88881689 -6.13281341]
 [ 2.86302037 -5.6338604 ]
 [ 3.31226514 -6.19396782]
 [ 2.92399691 -5.83519737]
 [ 3.2008114  -5.71259155]
 [ 2.96810819 -5.75475549]
 [ 2.2954854  -5.4563393 ]
 [ 3.20821456 -5.42024641]
 [ 3.15517201 -5.28351414]
 [ 3.00342587 -5.17566739]
 [ 3.0422871  -5.45261105]
 [ 2.94895215 -5.68940829]
 [ 2.87152183 -5.6340138 ]
 [ 2.87849519 -5.1246479 ]
 [ 2.92288105 -5.11733065]
 [ 3.10126576 -5.73280374]
 [ 2.86370642 -6.13470636]
 [ 2.91418362 -6.41474566]
 [ 2.83749841 -5.20803203]
 [ 2.64434325 -5.39191683]
 [ 2.88611463 -5.92152374]
 

# Questão 2
#### Implemente o algoritmo do k-means na linguagem de programação de sua preferência e inicialize este algoritmo com k=3 centros c1=[5.1,3.5,1.4,0.2], c2=[4.9,3.0,1.4,0.2], c3=[4.7,3.2,1.3,0.2].

In [76]:
iris_classes = []
for c in iris_classnames:
    if c == 'Iris-setosa':
        iris_classes.append(0)
    elif c == 'Iris-versicolor':
        iris_classes.append(1)
    elif c == 'Iris-virginica':
        iris_classes.append(2)
        
iris_classes = np.array(iris_classes)

In [154]:
# def dist(a, b):
#     return np.linalg.norm(np.array(a) - np.array(b))

def kmeans(dataset, K, centroids, stop_condition):
    curr_centroids = centroids
    last_centroids = centroids
    changes = True
#     iterations=0
    while changes:
        clusters = [[] for i in range(K)]
        for i in range(len(dataset)):
            distances = [np.linalg.norm(dataset[i] - c) for c in curr_centroids]
            clusters[np.argmin(distances)].append(dataset[i])
        curr_centroids = [np.mean(c, axis=0) for c in clusters]
        changes = (alg.norm(np.array(curr_centroids) - np.array(last_centroids) > stop_condition))
        last_centroids = curr_centroids
#         iterations+=1

#     print(iterations)
    return clusters, curr_centroids

a) Após a convergência, qual o valor dos centros?

In [163]:
c1 = [5.1,3.5,1.4,0.2]
c2= [4.9,3.0,1.4,0.2]
c3= [4.7,3.2,1.3,0.2]

clusters, centroids = kmeans(iris, 3, [c1, c2, c3], 0)
for c in centroids:
    print(c)

[6.85384615 3.07692308 5.71538462 2.05384615]
[5.88360656 2.74098361 4.38852459 1.43442623]
[5.006 3.418 1.464 0.244]


b) Qual o centro mais próximo do centro da classe “Iris-setosa”
<br />
c) Qual o centro mais próximo do centro da classe “Iris-versicolor”
<br />
d) Qual o centro mais próximo do centro da classe “Iris-virginica”

In [179]:
setosa_centroid = np.mean([iris[i] for i in range(len(iris)) if iris_classes[i]==0], axis=0)
near_setosa = centroids[np.argmin([np.linalg.norm(c - setosa_centroid) for c in centroids])]
print('a) Setosa nearest centroid:')
print(setosa_centroid)
print(near_setosa)
print()

versicolor_centroid = np.mean([iris[i] for i in range(len(iris)) if iris_classes[i]==1], axis=0)
near_versicolor = centroids[np.argmin([np.linalg.norm(c - versicolor_centroid) for c in centroids])]
print('a) Versicolor nearest centroid:')
print(versicolor_centroid)
print(near_versicolor)
print()

virginica_centroid = np.mean([iris[i] for i in range(len(iris)) if iris_classes[i]==2], axis=0)
near_virginica = centroids[np.argmin([np.linalg.norm(c - virginica_centroid) for c in centroids])]
print('a) Virginica nearest centroid:')
print(virginica_centroid)
print(near_virginica)



a) Setosa nearest centroid:
[5.006 3.418 1.464 0.244]
[5.006 3.418 1.464 0.244]

a) Versicolor nearest centroid:
[5.936 2.77  4.26  1.326]
[5.88360656 2.74098361 4.38852459 1.43442623]

a) Virginica nearest centroid:
[6.588 2.974 5.552 2.026]
[6.85384615 3.07692308 5.71538462 2.05384615]


# Questão 3
#### Implemente o algoritmo do KNN na linguagem de programação de sua preferência.

In [260]:
def most_common(lst):
    return max(set(lst), key=lst.count)

def knn(dataset, sample, k):
    #dataset: (attributes, class labels)
    data, labels = [x[0] for x in dataset], [x[1] for x in dataset]
    
    total_dist = data - np.repeat(np.array(sample)[np.newaxis], len(data), axis=0)
    norm = np.sum(total_dist*total_dist, axis=1)
    neighbors = list(zip(norm, labels))
    neighbors = sorted(neighbors, key=lambda tup: tup[0])
    closest_n = [atribute[1] for atribute in neighbors[:k]]
    
    return most_common(closest_n)

In [267]:
dataset = list(zip(iris, iris_classes))
trainning, test = train_test_split(dataset, test_size = 0.3)
# print(test[0][0])
# print(trainning[0])
success_rate = 0
for sample in test:
    n = knn(trainning, sample[0], 3)
    success_rate += (n == sample[1])

success_rate /= len(test)
print(success_rate)

0.9333333333333333


45